import fs from 'fs';
import path from 'path';

const productsPath = path.resolve('src/data/products.js');
let content = fs.readFileSync(productsPath, 'utf8');

// Extra catalog items for sections with distinct high-quality ice cream images
const sectionItems = [
  // Family Packs
  {
    id: 'fp1',
    name: '1L Vanilla Family Pack',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Vanilla',
    category: 'family-packs',
    price: 249,
    mrp: 320,
    rating: '4.8',
    reviewsCount: 150,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: '1 Litre pure milk vanilla ice cream tub. Family favorite for celebrations.',
  },
  {
    id: 'fp2',
    name: '1L Chocolate Family Pack',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Chocolate',
    category: 'family-packs',
    price: 259,
    mrp: 330,
    rating: '4.9',
    reviewsCount: 180,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: '1 Litre rich chocolate fudge ice cream tub packed with cocoa flavor.',
  },
  {
    id: 'fp3',
    name: 'Party Pack 2L Double Fudge',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Chocolate',
    category: 'family-packs',
    price: 449,
    mrp: 560,
    rating: '4.8',
    reviewsCount: 210,
    stock: 15,
    image: 'https://images.unsplash.com/photo-1576506295286-5cda18df43e7?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    isBestseller: true,
    description: '2 Litres jumbo party tub filled with double chocolate fudge and vanilla swirls.',
  },
  {
    id: 'fp4',
    name: 'Triple Flavor Pack 1.5L',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Mixed',
    category: 'family-packs',
    price: 399,
    mrp: 499,
    rating: '4.7',
    reviewsCount: 140,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: false,
    description: '1.5 Litres tri-color tub: Vanilla, Chocolate, and Strawberry scoops.',
  },
  {
    id: 'fp5',
    name: 'Premium Butterscotch Pack 1L',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Butterscotch',
    category: 'family-packs',
    price: 349,
    mrp: 420,
    rating: '4.8',
    reviewsCount: 165,
    stock: 22,
    image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: '1 Litre tub loaded with golden cashew crunchies and butterscotch ribbon.',
  },
  {
    id: 'fp6',
    name: 'Festival Celebration Pack 2.5L',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Kesar Pista',
    category: 'family-packs',
    price: 599,
    mrp: 749,
    rating: '4.9',
    reviewsCount: 230,
    stock: 12,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    isBestseller: true,
    description: '2.5 Litres royal kulfi celebration tub with Kashmiri saffron and pistachios.',
  },

  // Sundaes
  {
    id: 'sd1',
    name: 'Hot Fudge Brownie Sundae',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Brownie',
    category: 'sundaes',
    price: 189,
    mrp: 220,
    rating: '4.9',
    reviewsCount: 310,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1551106652-a5bcf4b29ab6?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Warm chocolate brownie topped with vanilla scoops, hot chocolate fudge, and nuts.',
  },
  {
    id: 'sd2',
    name: 'Belgian Dark Chocolate Sundae',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Chocolate',
    category: 'sundaes',
    price: 209,
    mrp: 240,
    rating: '4.8',
    reviewsCount: 280,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    isBestseller: true,
    description: 'Triple scoops of 70% dark Belgian chocolate gelato drizzled with dark ganache.',
  },
  {
    id: 'sd3',
    name: 'Berry Blast Sundae Glass',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Berry',
    category: 'sundaes',
    price: 169,
    mrp: 199,
    rating: '4.7',
    reviewsCount: 190,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1516559828984-fb3b99548b21?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: false,
    description: 'Strawberry and blackcurrant scoops topped with real berry compote and whipped cream.',
  },
  {
    id: 'sd4',
    name: 'KitKat Cookie Fudge Sundae',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Chocolate',
    category: 'sundaes',
    price: 199,
    mrp: 230,
    rating: '4.9',
    reviewsCount: 340,
    stock: 28,
    image: 'https://images.unsplash.com/photo-1516750105099-4b8a83e217ee?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Crunchy KitKat bars crushed over vanilla fudge scoops with chocolate syrup.',
  },
  {
    id: 'sd5',
    name: 'Oreo Choco Crunch Sundae',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Oreo',
    category: 'sundaes',
    price: 189,
    mrp: 210,
    rating: '4.8',
    reviewsCount: 260,
    stock: 22,
    image: 'https://images.unsplash.com/photo-1549395156-e0c1fe6fc7a5?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Dark cocoa biscuit crumbs, cookies & cream ice cream, topped with chocolate sauce.',
  },

  // Gelato
  {
    id: 'gl1',
    name: 'Belgian Chocolate Gelato Scoop',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Chocolate',
    category: 'gelato',
    price: 149,
    mrp: 175,
    rating: '4.9',
    reviewsCount: 220,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Authentic Italian dense dark chocolate gelato crafted with imported cocoa.',
  },
  {
    id: 'gl2',
    name: 'Blueberry Swirl Gelato',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Blueberry',
    category: 'gelato',
    price: 139,
    mrp: 160,
    rating: '4.7',
    reviewsCount: 175,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    isBestseller: false,
    description: 'Smooth artisan gelato swirled with wild mountain blueberry pulp.',
  },
  {
    id: 'gl3',
    name: 'Pistachio Sicilian Gelato',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Pistachio',
    category: 'gelato',
    price: 159,
    mrp: 185,
    rating: '4.8',
    reviewsCount: 195,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Nutty, rich Sicilian pistachio gelato with toasted pistachio crunch.',
  },
  {
    id: 'gl4',
    name: 'Salted Caramel Butter Gelato',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Caramel',
    category: 'gelato',
    price: 159,
    mrp: 185,
    rating: '4.8',
    reviewsCount: 210,
    stock: 22,
    image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Silky caramel gelato blended with sea salt and buttery butterscotch ribbon.',
  },

  // Kulfi
  {
    id: 'kl1',
    name: 'Traditional Malai Matka Kulfi',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Malai',
    category: 'kulfi',
    price: 79,
    mrp: 95,
    rating: '4.9',
    reviewsCount: 350,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Slow-cooked condensed milk rabri kulfi infused with cardamom and almonds.',
  },
  {
    id: 'kl2',
    name: 'Royal Kesar Pista Kulfi',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Kesar Pista',
    category: 'kulfi',
    price: 89,
    mrp: 105,
    rating: '4.9',
    reviewsCount: 380,
    stock: 35,
    image: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Kashmiri saffron and green pistachio rabri kulfi slice.',
  },
  {
    id: 'kl3',
    name: 'Alphonso Mango Kulfi Slice',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Mango',
    category: 'kulfi',
    price: 89,
    mrp: 105,
    rating: '4.8',
    reviewsCount: 290,
    stock: 30,
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    isBestseller: true,
    description: 'Pure Ratnagiri Alphonso mango pulp blended into thick rabri kulfi.',
  },

  // Milkshakes
  {
    id: 'ms1',
    name: 'Thick Belgian Chocolate Milkshake (300 ml)',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Chocolate',
    category: 'milkshakes',
    price: 149,
    mrp: 170,
    rating: '4.8',
    reviewsCount: 270,
    stock: 25,
    image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: true,
    description: 'Thick milk shake blended with real dark Belgian chocolate ice cream.',
  },
  {
    id: 'ms2',
    name: 'Strawberry Thickshake (300 ml)',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Strawberry',
    category: 'milkshakes',
    price: 139,
    mrp: 160,
    rating: '4.7',
    reviewsCount: 180,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1553787499-6f9133860278?auto=format&fit=crop&w=600&q=80',
    isNew: false,
    isBestseller: false,
    description: 'Refreshing shake made with real strawberry scoops and cold whole milk.',
  },
  {
    id: 'ms3',
    name: 'Oreo Cookie Crunch Milkshake (300 ml)',
    brand: 'Scoop & Co.',
    brandId: 'scoop-co',
    flavor: 'Oreo',
    category: 'milkshakes',
    price: 159,
    mrp: 180,
    rating: '4.9',
    reviewsCount: 320,
    stock: 28,
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=600&q=80',
    isNew: true,
    isBestseller: true,
    description: 'Blended Oreo cookies with creamy vanilla ice cream, topped with cookie dust.',
  },
];

// Append section items to main products array if not present
const newItemsStr = sectionItems
  .map((item) => {
    return `  {\n    id: '${item.id}',\n    name: '${item.name}',\n    brand: '${item.brand}',\n    brandId: '${item.brandId}',\n    flavor: '${item.flavor}',\n    category: '${item.category}',\n    price: ${item.price},\n    mrp: ${item.mrp},\n    rating: '${item.rating}',\n    reviewsCount: ${item.reviewsCount},\n    stock: ${item.stock},\n    image: '${item.image}',\n    isNew: ${item.isNew},\n    isBestseller: ${item.isBestseller},\n    description: '${item.description}',\n  },`;
  })
  .join('\n');

// Find insertion point before `export const familyPacks = [`
const insertPos = content.indexOf('export const familyPacks = [');
if (insertPos !== -1) {
  content = content.slice(0, insertPos) + '// --- POPULAR & SECTION EXCLUSIVES ---\n' + newItemsStr + '\n];\n\n' + content.slice(insertPos);
  // Also clean closing brackets before
  content = content.replace('];\n// --- POPULAR & SECTION EXCLUSIVES ---', '// --- POPULAR & SECTION EXCLUSIVES ---');
  fs.writeFileSync(productsPath, content, 'utf8');
  console.log('Successfully merged section products into main catalog!');
}
